# 🧠 Deep Learning Fundamentals using Loan Data

## Objective
This notebook introduces **Deep Learning concepts** using:
- A **Single-Layer Neural Network**
- A **Multi-Layer Neural Network (MLP)**

We apply them to a real **loan approval classification problem**.

Dataset:
➡️ hdfc_loan_dataset_full_enriched.csv

## 📘 What is Deep Learning?

Deep Learning is a subset of Machine Learning that uses
**Neural Networks with multiple layers** to learn complex patterns.

### Comparison
| Model | Capability |
|------|-----------|
| Linear / Logistic Regression | Linear relationships |
| Single-Layer NN | Slightly non-linear |
| Multi-Layer NN | Complex non-linear patterns |

Deep Learning is widely used in:
- Credit risk modeling
- Fraud detection
- Recommendation systems

## 🧠 Neural Network Basics

### Components:
- **Input Layer** → receives features
- **Hidden Layer(s)** → learns representations
- **Output Layer** → prediction

Each neuron performs:
Weighted Sum → Activation Function → Output

In [ ]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/datasets/hdfc_loan_dataset_full_enriched.csv")
df.head()

Mounted at /content/drive

,Loan_ID,Bank,Customer_Name,Gender,Married,Dependents,Education,Employment_Status,Applicant_Income,Coapplicant_Income,...,Loan_to_Annual_Income,Customer_Sentiment,Religion,State,City,PIN_Code,Aadhaar_Synthetic,Phone_Number,Email,Occupation
0,HDFC100001,HDFC Bank,Rohan Verma,Male,No,2,Graduate,Salaried,56976,0,...,11.747,Positive,Hindu,Delhi,Dwarka,857743,6.940000e+11,9068671773,rohan.verma@example.in,Farmer
1,HDFC100002,HDFC Bank,Rohan Verma,Male,No,0,Graduate,Unemployed,1856,0,...,40.381,Negative,Hindu,Punjab,Ludhiana,863836,6.330000e+11,9990772625,rohan.verma@example.in,Civil Engineer
2,HDFC100003,HDFC Bank,Aditya Nair,Female,Yes,0,Graduate,Salaried,64553,0,...,3.082,Positive,Hindu,Maharashtra,Nagpur,834796,1.660000e+11,9195085016,aditya.nair@example.in,Medical Representative
3,HDFC100004,HDFC Bank,Ananya Joshi,Male,No,0,Graduate,Salaried,88450,0,...,0.621,Negative,Hindu,Gujarat,Vadodara,438590,5.528183e+10,9179335548,ananya.joshi@example.in,Marketing Executive
4,HDFC100005,HDFC Bank,Harpreet Singh,Male,Yes,3,Graduate,Self-Employed,9539,0,...,1.736,Neutral,Sikh,West Bengal,Kolkata,495224,1.560000e+11,9795137116,harpreet.singh@example.in,Shopkeeper

In [ ]:
num_features = [
    'Dependents', 'Applicant_Income', 'Coapplicant_Income',
    'Loan_Amount', 'Loan_Term_Months', 'Credit_History',
    'Age', 'CIBIL_Score', 'Annual_Household_Income',
    'Debt_to_Income_Ratio', 'Existing_EMIs',
    'Number_of_Previous_Loans', 'Default_History_Count',
    'Employment_Length_Years', 'Asset_Value',
    'Monthly_Expense', 'Loan_to_Annual_Income'
]

X = df[num_features]
y = df['Loan_Status']

In [ ]:
encoder = LabelEncoder()
y_encoded = encoder.fit_transform(y)

encoder.classes_

array(['Approved', 'Rejected'], dtype=object)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y_encoded, test_size=0.2, random_state=42, stratify=y_encoded
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

## 🔹 Single-Layer Neural Network

A single-layer neural network:
- Has **no hidden layers**
- Works similarly to Logistic Regression
- Learns linear decision boundaries

Used mainly for:
- Baseline deep learning models
- Comparison with deeper networks

In [ ]:
single_layer_model = Sequential([
    Dense(1, activation='sigmoid', input_shape=(X_train_scaled.shape[1],))
])

single_layer_model.compile(
    optimizer=Adam(learning_rate=0.01),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

single_layer_model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 1)              │            18 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 18 (72.00 B)

 Trainable params: 18 (72.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
single_layer_model.fit(
    X_train_scaled, y_train,
    epochs=30,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)

Epoch 1/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.6984 - loss: 0.5929 - val_accuracy: 0.7250 - val_loss: 0.5428
Epoch 2/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7688 - loss: 0.4825 - val_accuracy: 0.7500 - val_loss: 0.4673
Epoch 3/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7969 - loss: 0.4224 - val_accuracy: 0.7750 - val_loss: 0.4227
Epoch 4/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8297 - loss: 0.3865 - val_accuracy: 0.7875 - val_loss: 0.3916
Epoch 5/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8453 - loss: 0.3652 - val_accuracy: 0.8062 - val_loss: 0.3697
Epoch 6/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8484 - loss: 0.3504 - val_accuracy: 0.8000 - val_loss: 0.3542
Epoch 7/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8469 - loss: 0.3380 - val_accuracy: 0.8125 - val_loss: 0.3459
Epoch 8/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8547 - loss: 0.3306 - val_accuracy: 0.8250 - val_loss: 0.3375
Epoch 9/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8500 - loss: 0.3253 - val_accuracy: 0.8375 - val_loss: 0.3310
Epoch 10/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8531 - loss: 0.3210 - val_accuracy: 0.8438 - val_loss: 0.3271
Epoch 11/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8531 - loss: 0.3181 - val_accuracy: 0.8438 - val_loss: 0.3245
Epoch 12/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8516 - loss: 0.3152 - val_accuracy: 0.8500 - val_loss: 0.3237
Epoch 13/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8531 - loss: 0.3124 - val_accuracy: 0.8500 - val_loss: 0.3200
Epoch 14/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8578 - loss: 0.3117 - val_accuracy: 0.8500 - val_loss: 0.3178
Epoch 15/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8609 - loss: 0.3100 - val_accuracy: 0.8438 - val_loss: 0.3169
Epoch 16/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8578 - loss: 0.3091 - val_accuracy: 0.8500 - val_loss: 0.3177
Epoch 17/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8578 - loss: 0.3094 - val_accuracy: 0.8500 - val_loss: 0.3185
Epoch 18/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8562 - loss: 0.3078 - val_accuracy: 0.8625 - val_loss: 0.3156
Epoch 19/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8547 - loss: 0.3073 - val_accuracy: 0.8562 - val_loss: 0.3142
Epoch 20/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8594 - loss: 0.3066 - val_accuracy: 0.8562 - val_loss: 0.3161
Epoch 21/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8578 - loss: 0.3063 - val_accuracy: 0.8562 - val_loss: 0.3156
Epoch 22/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8594 - loss: 0.3057 - val_accuracy: 0.8687 - val_loss: 0.3150
Epoch 23/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8594 - loss: 0.3056 - val_accuracy: 0.8562 - val_loss: 0.3136
Epoch 24/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8594 - loss: 0.3055 - val_accuracy: 0.8562 - val_loss: 0.3153
Epoch 25/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8594 - loss: 0.3053 - val_accuracy: 0.8562 - val_loss: 0.3143
Epoch 26/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8578 - loss: 0.3047 - val_accuracy: 0.8687 - val_loss: 0.3131
Epoch 27/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8562 - loss: 0.3048 - val_accuracy: 0.8625 - val_loss: 0.3145
Epoch 28/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8562 - loss: 0.3055 - val_accuracy: 0.8625 - val_loss: 0.3150
Epoch 29/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8609 - loss: 0.3038 - val_accuracy: 0.8562 - val_loss: 0.3139
Epoch 30/30
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8594 - loss: 0.3044 - val_accuracy: 0.8562 - val_loss: 0.3137

In [ ]:
single_loss, single_acc = single_layer_model.evaluate(X_test_scaled, y_test)
print("Single-Layer NN Accuracy:", single_acc)

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8150 - loss: 0.4562
Single-Layer NN Accuracy: 0.8149999976158142

## 🔹 Multi-Layer Neural Network (MLP)

A Multi-Layer Perceptron:
- Has **one or more hidden layers**
- Learns complex non-linear patterns
- Forms the foundation of deep learning

This is the most common DL model for tabular data.

In [ ]:
mlp_model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train_scaled.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid')
])

mlp_model.compile(
    optimizer=Adam(learning_rate=0.001),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

mlp_model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_1 (Dense)                 │ (None, 64)             │         1,152 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,265 (12.75 KB)

 Trainable params: 3,265 (12.75 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
mlp_model.fit(
    X_train_scaled, y_train,
    epochs=40,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)

Epoch 1/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - accuracy: 0.7094 - loss: 0.5794 - val_accuracy: 0.7812 - val_loss: 0.5114
Epoch 2/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - accuracy: 0.8125 - loss: 0.4498 - val_accuracy: 0.7875 - val_loss: 0.4403
Epoch 3/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - accuracy: 0.8453 - loss: 0.3759 - val_accuracy: 0.8062 - val_loss: 0.3975
Epoch 4/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.8562 - loss: 0.3321 - val_accuracy: 0.8000 - val_loss: 0.3699
Epoch 5/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.8750 - loss: 0.2996 - val_accuracy: 0.8125 - val_loss: 0.3540
Epoch 6/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8828 - loss: 0.2770 - val_accuracy: 0.8250 - val_loss: 0.3421
Epoch 7/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - accuracy: 0.8906 - loss: 0.2586 - val_accuracy: 0.8438 - val_loss: 0.3375
Epoch 8/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - accuracy: 0.8984 - loss: 0.2457 - val_accuracy: 0.8313 - val_loss: 0.3319
Epoch 9/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - accuracy: 0.9078 - loss: 0.2354 - val_accuracy: 0.8250 - val_loss: 0.3338
Epoch 10/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.9109 - loss: 0.2250 - val_accuracy: 0.8375 - val_loss: 0.3287
Epoch 11/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.9125 - loss: 0.2173 - val_accuracy: 0.8500 - val_loss: 0.3300
Epoch 12/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.9187 - loss: 0.2098 - val_accuracy: 0.8438 - val_loss: 0.3339
Epoch 13/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9219 - loss: 0.2025 - val_accuracy: 0.8438 - val_loss: 0.3361
Epoch 14/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9187 - loss: 0.1975 - val_accuracy: 0.8375 - val_loss: 0.3301
Epoch 15/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.9266 - loss: 0.1914 - val_accuracy: 0.8313 - val_loss: 0.3315
Epoch 16/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.9266 - loss: 0.1860 - val_accuracy: 0.8313 - val_loss: 0.3320
Epoch 17/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9266 - loss: 0.1825 - val_accuracy: 0.8375 - val_loss: 0.3336
Epoch 18/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9328 - loss: 0.1758 - val_accuracy: 0.8313 - val_loss: 0.3358
Epoch 19/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.9375 - loss: 0.1741 - val_accuracy: 0.8438 - val_loss: 0.3358
Epoch 20/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9359 - loss: 0.1723 - val_accuracy: 0.8562 - val_loss: 0.3350
Epoch 21/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9406 - loss: 0.1675 - val_accuracy: 0.8375 - val_loss: 0.3442
Epoch 22/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.9312 - loss: 0.1657 - val_accuracy: 0.8375 - val_loss: 0.3396
Epoch 23/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9359 - loss: 0.1623 - val_accuracy: 0.8375 - val_loss: 0.3413
Epoch 24/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9391 - loss: 0.1580 - val_accuracy: 0.8375 - val_loss: 0.3454
Epoch 25/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9453 - loss: 0.1536 - val_accuracy: 0.8375 - val_loss: 0.3455
Epoch 26/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9406 - loss: 0.1510 - val_accuracy: 0.8375 - val_loss: 0.3455
Epoch 27/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9453 - loss: 0.1472 - val_accuracy: 0.8375 - val_loss: 0.3453
Epoch 28/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9484 - loss: 0.1421 - val_accuracy: 0.8313 - val_loss: 0.3542
Epoch 29/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9516 - loss: 0.1382 - val_accuracy: 0.8375 - val_loss: 0.3490
Epoch 30/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9453 - loss: 0.1409 - val_accuracy: 0.8375 - val_loss: 0.3542
Epoch 31/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9516 - loss: 0.1342 - val_accuracy: 0.8500 - val_loss: 0.3501
Epoch 32/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9563 - loss: 0.1305 - val_accuracy: 0.8438 - val_loss: 0.3592
Epoch 33/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9531 - loss: 0.1273 - val_accuracy: 0.8500 - val_loss: 0.3581
Epoch 34/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9547 - loss: 0.1258 - val_accuracy: 0.8313 - val_loss: 0.3628
Epoch 35/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9516 - loss: 0.1228 - val_accuracy: 0.8313 - val_loss: 0.3608
Epoch 36/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9531 - loss: 0.1240 - val_accuracy: 0.8562 - val_loss: 0.3605
Epoch 37/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9625 - loss: 0.1180 - val_accuracy: 0.8562 - val_loss: 0.3631
Epoch 38/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9641 - loss: 0.1131 - val_accuracy: 0.8500 - val_loss: 0.3693
Epoch 39/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9609 - loss: 0.1120 - val_accuracy: 0.8313 - val_loss: 0.3801
Epoch 40/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9672 - loss: 0.1085 - val_accuracy: 0.8625 - val_loss: 0.3682

In [ ]:
mlp_loss, mlp_acc = mlp_model.evaluate(X_test_scaled, y_test)
print("Multi-Layer NN Accuracy:", mlp_acc)

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7950 - loss: 0.5553
Multi-Layer NN Accuracy: 0.7950000166893005

## 📊 Model Comparison

In [ ]:
pd.DataFrame({
    'Model': ['Single-Layer NN', 'Multi-Layer NN'],
    'Accuracy': [single_acc, mlp_acc]
})

             Model  Accuracy
0  Single-Layer NN     0.815
1   Multi-Layer NN     0.795

## 🏦 Business Interpretation

- Single-Layer NN ≈ Logistic Regression baseline
- Multi-Layer NN captures interactions between:
  - Income
  - Credit score
  - Debt ratio
- Better suited for complex loan approval decisions

⚠️ Deep learning requires:
- Proper scaling
- Careful tuning
- Explainability (next topic)

## 🧠 Practice Exercises

1. Increase the number of hidden layers and observe overfitting.
2. Change activation functions (ReLU → Tanh).
3. Reduce learning rate and compare convergence.
4. Compare DL accuracy with Random Forest from previous notebook.

In [ ]:
# Increase the number of hidden layers and observe overfitting.
relu_model = Sequential([
    Dense(128, activation='relu', input_shape=(X_train_scaled.shape[1],)),
    Dense(64, activation='relu'),
    Dense(32, activation='relu'),
    Dense(16, activation='relu'),
    Dense(1, activation='sigmoid')
])

relu_model.compile(
    optimizer=Adam(learning_rate=0.001),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

history = relu_model.fit(
    X_train_scaled, y_train,
    epochs=50,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)

Epoch 1/50

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - accuracy: 0.7047 - loss: 0.5953 - val_accuracy: 0.8062 - val_loss: 0.5051
Epoch 2/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8516 - loss: 0.4102 - val_accuracy: 0.8125 - val_loss: 0.3883
Epoch 3/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8750 - loss: 0.3118 - val_accuracy: 0.8500 - val_loss: 0.3245
Epoch 4/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8984 - loss: 0.2567 - val_accuracy: 0.8625 - val_loss: 0.3172
Epoch 5/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8969 - loss: 0.2245 - val_accuracy: 0.8438 - val_loss: 0.3320
Epoch 6/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9094 - loss: 0.2145 - val_accuracy: 0.8500 - val_loss: 0.3319
Epoch 7/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9266 - loss: 0.1933 - val_accuracy: 0.8500 - val_loss: 0.3374
Epoch 8/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9266 - loss: 0.1819 - val_accuracy: 0.8562 - val_loss: 0.3307
Epoch 9/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9359 - loss: 0.1750 - val_accuracy: 0.8687 - val_loss: 0.3468
Epoch 10/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9359 - loss: 0.1643 - val_accuracy: 0.8562 - val_loss: 0.3568
Epoch 11/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9438 - loss: 0.1518 - val_accuracy: 0.8625 - val_loss: 0.3546
Epoch 12/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9500 - loss: 0.1368 - val_accuracy: 0.8625 - val_loss: 0.3641
Epoch 13/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9609 - loss: 0.1240 - val_accuracy: 0.8562 - val_loss: 0.3842
Epoch 14/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9672 - loss: 0.1150 - val_accuracy: 0.8562 - val_loss: 0.3978
Epoch 15/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9656 - loss: 0.1084 - val_accuracy: 0.8500 - val_loss: 0.4334
Epoch 16/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9734 - loss: 0.0942 - val_accuracy: 0.8313 - val_loss: 0.4430
Epoch 17/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9797 - loss: 0.0842 - val_accuracy: 0.8375 - val_loss: 0.4720
Epoch 18/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9812 - loss: 0.0766 - val_accuracy: 0.8562 - val_loss: 0.4634
Epoch 19/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9844 - loss: 0.0737 - val_accuracy: 0.8500 - val_loss: 0.4893
Epoch 20/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9875 - loss: 0.0645 - val_accuracy: 0.8125 - val_loss: 0.5323
Epoch 21/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9891 - loss: 0.0587 - val_accuracy: 0.8438 - val_loss: 0.5432
Epoch 22/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9906 - loss: 0.0553 - val_accuracy: 0.8500 - val_loss: 0.5001
Epoch 23/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9953 - loss: 0.0451 - val_accuracy: 0.8500 - val_loss: 0.5369
Epoch 24/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9953 - loss: 0.0388 - val_accuracy: 0.8438 - val_loss: 0.5790
Epoch 25/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9937 - loss: 0.0360 - val_accuracy: 0.8250 - val_loss: 0.6304
Epoch 26/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9969 - loss: 0.0314 - val_accuracy: 0.8438 - val_loss: 0.6199
Epoch 27/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9969 - loss: 0.0268 - val_accuracy: 0.8500 - val_loss: 0.6442
Epoch 28/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9969 - loss: 0.0230 - val_accuracy: 0.8500 - val_loss: 0.6712
Epoch 29/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9969 - loss: 0.0221 - val_accuracy: 0.8562 - val_loss: 0.6777
Epoch 30/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9969 - loss: 0.0207 - val_accuracy: 0.8438 - val_loss: 0.7037
Epoch 31/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9953 - loss: 0.0200 - val_accuracy: 0.8375 - val_loss: 0.6768
Epoch 32/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9969 - loss: 0.0176 - val_accuracy: 0.8500 - val_loss: 0.6746
Epoch 33/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9984 - loss: 0.0139 - val_accuracy: 0.8438 - val_loss: 0.7192
Epoch 34/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9984 - loss: 0.0120 - val_accuracy: 0.8438 - val_loss: 0.7674
Epoch 35/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9984 - loss: 0.0111 - val_accuracy: 0.8375 - val_loss: 0.7591
Epoch 36/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9984 - loss: 0.0096 - val_accuracy: 0.8375 - val_loss: 0.7871
Epoch 37/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9984 - loss: 0.0088 - val_accuracy: 0.8438 - val_loss: 0.7881
Epoch 38/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9984 - loss: 0.0083 - val_accuracy: 0.8375 - val_loss: 0.8038
Epoch 39/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9984 - loss: 0.0077 - val_accuracy: 0.8375 - val_loss: 0.8160
Epoch 40/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9984 - loss: 0.0068 - val_accuracy: 0.8375 - val_loss: 0.8329
Epoch 41/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9984 - loss: 0.0063 - val_accuracy: 0.8313 - val_loss: 0.8532
Epoch 42/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9984 - loss: 0.0061 - val_accuracy: 0.8375 - val_loss: 0.8625
Epoch 43/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9984 - loss: 0.0055 - val_accuracy: 0.8438 - val_loss: 0.8605
Epoch 44/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9984 - loss: 0.0049 - val_accuracy: 0.8313 - val_loss: 0.8965
Epoch 45/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9984 - loss: 0.0050 - val_accuracy: 0.8438 - val_loss: 0.8816
Epoch 46/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9984 - loss: 0.0041 - val_accuracy: 0.8438 - val_loss: 0.9116
Epoch 47/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9984 - loss: 0.0033 - val_accuracy: 0.8438 - val_loss: 0.9303
Epoch 48/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 0.0026 - val_accuracy: 0.8500 - val_loss: 0.9397
Epoch 49/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.0022 - val_accuracy: 0.8500 - val_loss: 0.9523
Epoch 50/50
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0018 - val_accuracy: 0.8500 - val_loss: 0.9674

In [ ]:
relu_acc, relu_loss = relu_model.evaluate(X_test_scaled, y_test)
print("Multi-Layer NN Accuracy:", relu_acc)

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8050 - loss: 1.3012
Multi-Layer NN Accuracy: 1.3011895418167114

In [ ]:
# Change activation functions (ReLU → Tanh).
tanh_model = Sequential([
    Dense(64, activation='tanh', input_shape=(X_train_scaled.shape[1],)),
    Dense(64, activation='tanh'),
    Dense(32, activation='tanh'),
    Dense(1, activation='sigmoid')
])

tanh_model.compile(
    optimizer=Adam(learning_rate=0.001),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

tanh_model.fit(
    X_train_scaled, y_train,
    epochs=40,
    batch_size=32,
    validation_split=0.2
)

Epoch 1/40

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - accuracy: 0.7031 - loss: 0.5703 - val_accuracy: 0.8062 - val_loss: 0.4504
Epoch 2/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8250 - loss: 0.3924 - val_accuracy: 0.8188 - val_loss: 0.3574
Epoch 3/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8469 - loss: 0.3289 - val_accuracy: 0.8375 - val_loss: 0.3294
Epoch 4/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8578 - loss: 0.3078 - val_accuracy: 0.8500 - val_loss: 0.3216
Epoch 5/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8594 - loss: 0.3027 - val_accuracy: 0.8625 - val_loss: 0.3236
Epoch 6/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8625 - loss: 0.2949 - val_accuracy: 0.8562 - val_loss: 0.3168
Epoch 7/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8656 - loss: 0.2911 - val_accuracy: 0.8625 - val_loss: 0.3124
Epoch 8/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8672 - loss: 0.2828 - val_accuracy: 0.8562 - val_loss: 0.3179
Epoch 9/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8609 - loss: 0.2790 - val_accuracy: 0.8625 - val_loss: 0.3157
Epoch 10/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8766 - loss: 0.2730 - val_accuracy: 0.8438 - val_loss: 0.3104
Epoch 11/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8813 - loss: 0.2664 - val_accuracy: 0.8500 - val_loss: 0.3120
Epoch 12/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8922 - loss: 0.2621 - val_accuracy: 0.8625 - val_loss: 0.3100
Epoch 13/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8875 - loss: 0.2535 - val_accuracy: 0.8438 - val_loss: 0.3130
Epoch 14/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8922 - loss: 0.2512 - val_accuracy: 0.8750 - val_loss: 0.3091
Epoch 15/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8969 - loss: 0.2476 - val_accuracy: 0.8438 - val_loss: 0.3233
Epoch 16/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8938 - loss: 0.2389 - val_accuracy: 0.8562 - val_loss: 0.3113
Epoch 17/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9078 - loss: 0.2339 - val_accuracy: 0.8562 - val_loss: 0.3095
Epoch 18/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9125 - loss: 0.2229 - val_accuracy: 0.8313 - val_loss: 0.3174
Epoch 19/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9109 - loss: 0.2148 - val_accuracy: 0.8500 - val_loss: 0.3164
Epoch 20/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9172 - loss: 0.2107 - val_accuracy: 0.8375 - val_loss: 0.3237
Epoch 21/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9172 - loss: 0.2053 - val_accuracy: 0.8438 - val_loss: 0.3240
Epoch 22/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9187 - loss: 0.2030 - val_accuracy: 0.8438 - val_loss: 0.3300
Epoch 23/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9172 - loss: 0.1971 - val_accuracy: 0.8562 - val_loss: 0.3251
Epoch 24/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9109 - loss: 0.1913 - val_accuracy: 0.8438 - val_loss: 0.3360
Epoch 25/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9172 - loss: 0.1853 - val_accuracy: 0.8562 - val_loss: 0.3365
Epoch 26/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9250 - loss: 0.1813 - val_accuracy: 0.8438 - val_loss: 0.3458
Epoch 27/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9328 - loss: 0.1715 - val_accuracy: 0.8438 - val_loss: 0.3454
Epoch 28/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9297 - loss: 0.1696 - val_accuracy: 0.8562 - val_loss: 0.3366
Epoch 29/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9312 - loss: 0.1698 - val_accuracy: 0.8375 - val_loss: 0.3691
Epoch 30/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9391 - loss: 0.1641 - val_accuracy: 0.8562 - val_loss: 0.3482
Epoch 31/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9484 - loss: 0.1546 - val_accuracy: 0.8500 - val_loss: 0.3805
Epoch 32/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9359 - loss: 0.1569 - val_accuracy: 0.8562 - val_loss: 0.3679
Epoch 33/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9484 - loss: 0.1517 - val_accuracy: 0.8438 - val_loss: 0.3749
Epoch 34/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9547 - loss: 0.1498 - val_accuracy: 0.8500 - val_loss: 0.3697
Epoch 35/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9531 - loss: 0.1417 - val_accuracy: 0.8625 - val_loss: 0.3662
Epoch 36/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9531 - loss: 0.1418 - val_accuracy: 0.8562 - val_loss: 0.3888
Epoch 37/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9531 - loss: 0.1359 - val_accuracy: 0.8625 - val_loss: 0.3672
Epoch 38/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9547 - loss: 0.1317 - val_accuracy: 0.8500 - val_loss: 0.4085
Epoch 39/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9531 - loss: 0.1296 - val_accuracy: 0.8375 - val_loss: 0.3890
Epoch 40/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9531 - loss: 0.1353 - val_accuracy: 0.8438 - val_loss: 0.4337

In [ ]:
tanh_acc, tanh_loss = tanh_model.evaluate(X_test_scaled, y_test)
print("Multi-Layer NN Accuracy:", tanh_acc)

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8300 - loss: 0.5654
Multi-Layer NN Accuracy: 0.5654489398002625

In [ ]:
# Reduce learning rate and compare convergence.
low_lr_model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train_scaled.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid')
])

low_lr_model.compile(
    optimizer=Adam(learning_rate=0.0001),  # reduced LR
    loss='binary_crossentropy',
    metrics=['accuracy']
)

low_lr_model.fit(
    X_train_scaled, y_train,
    epochs=40,
    batch_size=32,
    validation_split=0.2
)

Epoch 1/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - accuracy: 0.6391 - loss: 0.6490 - val_accuracy: 0.6125 - val_loss: 0.6600
Epoch 2/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6766 - loss: 0.6261 - val_accuracy: 0.6250 - val_loss: 0.6399
Epoch 3/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7000 - loss: 0.6056 - val_accuracy: 0.6562 - val_loss: 0.6213
Epoch 4/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7188 - loss: 0.5868 - val_accuracy: 0.6875 - val_loss: 0.6046
Epoch 5/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7391 - loss: 0.5694 - val_accuracy: 0.7188 - val_loss: 0.5889
Epoch 6/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7531 - loss: 0.5533 - val_accuracy: 0.7250 - val_loss: 0.5743
Epoch 7/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7672 - loss: 0.5383 - val_accuracy: 0.7312 - val_loss: 0.5600
Epoch 8/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7797 - loss: 0.5239 - val_accuracy: 0.7500 - val_loss: 0.5471
Epoch 9/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7859 - loss: 0.5104 - val_accuracy: 0.7688 - val_loss: 0.5352
Epoch 10/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7953 - loss: 0.4979 - val_accuracy: 0.7750 - val_loss: 0.5237
Epoch 11/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7969 - loss: 0.4861 - val_accuracy: 0.7688 - val_loss: 0.5128
Epoch 12/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4749 - val_accuracy: 0.7750 - val_loss: 0.5028
Epoch 13/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8125 - loss: 0.4645 - val_accuracy: 0.7812 - val_loss: 0.4926
Epoch 14/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8125 - loss: 0.4542 - val_accuracy: 0.7937 - val_loss: 0.4835
Epoch 15/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8156 - loss: 0.4445 - val_accuracy: 0.7937 - val_loss: 0.4746
Epoch 16/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8234 - loss: 0.4354 - val_accuracy: 0.8125 - val_loss: 0.4661
Epoch 17/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8313 - loss: 0.4267 - val_accuracy: 0.8125 - val_loss: 0.4586
Epoch 18/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8328 - loss: 0.4186 - val_accuracy: 0.8062 - val_loss: 0.4509
Epoch 19/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8328 - loss: 0.4107 - val_accuracy: 0.8062 - val_loss: 0.4438
Epoch 20/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8391 - loss: 0.4031 - val_accuracy: 0.8062 - val_loss: 0.4372
Epoch 21/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8391 - loss: 0.3961 - val_accuracy: 0.8062 - val_loss: 0.4311
Epoch 22/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8391 - loss: 0.3894 - val_accuracy: 0.8188 - val_loss: 0.4250
Epoch 23/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8438 - loss: 0.3828 - val_accuracy: 0.8250 - val_loss: 0.4193
Epoch 24/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8484 - loss: 0.3767 - val_accuracy: 0.8313 - val_loss: 0.4142
Epoch 25/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8453 - loss: 0.3709 - val_accuracy: 0.8313 - val_loss: 0.4090
Epoch 26/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8484 - loss: 0.3653 - val_accuracy: 0.8313 - val_loss: 0.4044
Epoch 27/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8531 - loss: 0.3602 - val_accuracy: 0.8313 - val_loss: 0.3999
Epoch 28/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8562 - loss: 0.3552 - val_accuracy: 0.8313 - val_loss: 0.3956
Epoch 29/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8578 - loss: 0.3503 - val_accuracy: 0.8375 - val_loss: 0.3916
Epoch 30/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8547 - loss: 0.3460 - val_accuracy: 0.8438 - val_loss: 0.3880
Epoch 31/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8594 - loss: 0.3416 - val_accuracy: 0.8500 - val_loss: 0.3839
Epoch 32/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8578 - loss: 0.3372 - val_accuracy: 0.8500 - val_loss: 0.3808
Epoch 33/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8641 - loss: 0.3332 - val_accuracy: 0.8438 - val_loss: 0.3780
Epoch 34/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8672 - loss: 0.3293 - val_accuracy: 0.8438 - val_loss: 0.3751
Epoch 35/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8687 - loss: 0.3256 - val_accuracy: 0.8438 - val_loss: 0.3721
Epoch 36/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8703 - loss: 0.3219 - val_accuracy: 0.8438 - val_loss: 0.3696
Epoch 37/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8719 - loss: 0.3185 - val_accuracy: 0.8500 - val_loss: 0.3671
Epoch 38/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8781 - loss: 0.3151 - val_accuracy: 0.8438 - val_loss: 0.3647
Epoch 39/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8781 - loss: 0.3119 - val_accuracy: 0.8500 - val_loss: 0.3625
Epoch 40/40
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8781 - loss: 0.3090 - val_accuracy: 0.8500 - val_loss: 0.3604

In [ ]:
low_loss, low_acc = low_lr_model.evaluate(X_test_scaled, y_test)
print("Low LR Model Accuracy:", low_acc)

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8000 - loss: 0.4209
Low LR Model Accuracy: 0.800000011920929

In [ ]:
# Compare DL accuracy with Random Forest from previous notebook.
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf_model.fit(X_train, y_train)

rf_preds = rf_model.predict(X_test)

rf_acc = accuracy_score(y_test, rf_preds)

print("Random Forest Accuracy:", rf_acc)

Random Forest Accuracy: 0.84